---
- name: Manage Docker Containers
  hosts: vbox
  become: yes
  tasks:
    - name: Create a Docker network
      docker_network:
        name: my_network
        state: present

    - name: Run a web server container
      docker_container:
        name: web_server
        image: nginx
        state: started
        restart_policy: always
        networks:
          - name: my_network

    - name: Run a database container
      docker_container:
        name: db_server
        image: mysql:5.7
        state: started
        restart_policy: always
        env:
          MYSQL_ROOT_PASSWORD: root
        networks:
          - name: my_network
          
    - name: Remove a container
      docker_container:
        name: db_server
        state: absent