---
- name: Deploy Node.js Application
  hosts: vbox
  tasks:
    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
      become: yes

    - name: Ensure destination directory exists
      file:
        path: /home/ais
        state: directory
        owner: soultan
        group: soultan
        mode: '0755'
      become: yes

    - name: Copy application files
      copy:
        src: ./app.js
        dest: /home/ais/app.js
      become: yes

    - name: Copy package.json
      copy:
        src: ./package.json
        dest: /home/ais/package.json
      become: yes

    - name: Install dependencies
      npm:
        path: /home/ais
        state: present
      become: yes

    - name: Start Node.js application
      command: node /home/ais/app.js
      async: 10
      poll: 0
